# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Currency.destroy_all

Currency.create(code: "AED",name: "United Arab Emirates Dirham (AED)")
Currency.create(code: "AFN",name: "Afghan Afghani (AFN)")
Currency.create(code: "ALL",name: "Albanian Lek (ALL)")
Currency.create(code: "AMD",name: "Armenian Dram (AMD)")
Currency.create(code: "ANG",name: "Netherlands Antillean Guilder (ANG)")
Currency.create(code: "AOA",name: "Angolan Kwanza (AOA)")
Currency.create(code: "ARS",name: "Argentine Peso (ARS)")
Currency.create(code: "AUD",name: "Australian Dollar (AUD)")
Currency.create(code: "AWG",name: "Aruban Florin (AWG)")
Currency.create(code: "AZN",name: "Azerbaijani Manat (AZN)")
Currency.create(code: "BAM",name: "Bosnia-Herzegovina Convertible Mark (BAM)")
Currency.create(code: "BBD",name: "Barbadian Dollar (BBD)")
Currency.create(code: "BDT",name: "Bangladeshi Taka (BDT)")
Currency.create(code: "BGN",name: "Bulgarian Lev (BGN)")
Currency.create(code: "BHD",name: "Bahraini Dinar (BHD)")
Currency.create(code: "BIF",name: "Burundian Franc (BIF)")
Currency.create(code: "BMD",name: "Bermudan Dollar (BMD)")
Currency.create(code: "BND",name: "Brunei Dollar (BND)")
Currency.create(code: "BOB",name: "Bolivian Boliviano (BOB)")
Currency.create(code: "BRL",name: "Brazilian Real (BRL)")
Currency.create(code: "BSD",name: "Bahamian Dollar (BSD)")
Currency.create(code: "BTN",name: "Bhutanese Ngultrum (BTN)")
Currency.create(code: "BWP",name: "Botswanan Pula (BWP)")
Currency.create(code: "BZD",name: "Belize Dollar (BZD)")
Currency.create(code: "CAD",name: "Canadian Dollar (CAD)")
Currency.create(code: "CDF",name: "Congolese Franc (CDF)")
Currency.create(code: "CHF",name: "Swiss Franc (CHF)")
Currency.create(code: "CLF",name: "Chilean Unit of Account UF (CLF)")
Currency.create(code: "CLP",name: "Chilean Peso (CLP)")
Currency.create(code: "CNH",name: "Chinese Yuan Offshore (CNH)")
Currency.create(code: "CNY",name: "Chinese Yuan (CNY)")
Currency.create(code: "COP",name: "Colombian Peso (COP)")
Currency.create(code: "CUP",name: "Cuban Peso (CUP)")
Currency.create(code: "CVE",name: "Cape Verdean Escudo (CVE)")
Currency.create(code: "CZK",name: "Czech Republic Koruna (CZK)")
Currency.create(code: "DJF",name: "Djiboutian Franc (DJF)")
Currency.create(code: "DKK",name: "Danish Krone (DKK)")
Currency.create(code: "DOP",name: "Dominican Peso (DOP)")
Currency.create(code: "DZD",name: "Algerian Dinar (DZD)")
Currency.create(code: "EGP",name: "Egyptian Pound (EGP)")
Currency.create(code: "ERN",name: "Eritrean Nakfa (ERN)")
Currency.create(code: "ETB",name: "Ethiopian Birr (ETB)")
Currency.create(code: "EUR",name: "Euro (EUR)")
Currency.create(code: "FJD",name: "Fijian Dollar (FJD)")
Currency.create(code: "FKP",name: "Falkland Islands Pound (FKP)")
Currency.create(code: "GBP",name: "British Pound Sterling (GBP)")
Currency.create(code: "GEL",name: "Georgian Lari (GEL)")
Currency.create(code: "GHS",name: "Ghanaian Cedi (GHS)")
Currency.create(code: "GIP",name: "Gibraltar Pound (GIP)")
Currency.create(code: "GMD",name: "Gambian Dalasi (GMD)")
Currency.create(code: "GNF",name: "Guinean Franc (GNF)")
Currency.create(code: "GTQ",name: "Guatemalan Quetzal (GTQ)")
Currency.create(code: "GYD",name: "Guyanaese Dollar (GYD)")
Currency.create(code: "HKD",name: "Hong Kong Dollar (HKD)")
Currency.create(code: "HNL",name: "Honduran Lempira (HNL)")
Currency.create(code: "HRK",name: "Croatian Kuna (HRK)")
Currency.create(code: "HTG",name: "Haitian Gourde (HTG)")
Currency.create(code: "HUF",name: "Hungarian Forint (HUF)")
Currency.create(code: "IDR",name: "Indonesian Rupiah (IDR)")
Currency.create(code: "ILS",name: "Israeli New Sheqel (ILS)")
Currency.create(code: "INR",name: "Indian Rupee (INR)")
Currency.create(code: "IQD",name: "Iraqi Dinar (IQD)")
Currency.create(code: "IRR",name: "Iranian Rial (IRR)")
Currency.create(code: "ISK",name: "Icelandic Krona (ISK)")
Currency.create(code: "JEP",name: "Jersey Pound (JEP)")
Currency.create(code: "JMD",name: "Jamaican Dollar (JMD)")
Currency.create(code: "JOD",name: "Jordanian Dinar (JOD)")
Currency.create(code: "JPY",name: "Japanese Yen (JPY)")
Currency.create(code: "KES",name: "Kenyan Shilling (KES)")
Currency.create(code: "KGS",name: "Kyrgystani Som (KGS)")
Currency.create(code: "KHR",name: "Cambodian Riel (KHR)")
Currency.create(code: "KMF",name: "Comorian Franc (KMF)")
Currency.create(code: "KPW",name: "North Korean Won (KPW)")
Currency.create(code: "KRW",name: "South Korean Won (KRW)")
Currency.create(code: "KWD",name: "Kuwaiti Dinar (KWD)")
Currency.create(code: "KYD",name: "Cayman Islands Dollar (KYD)")
Currency.create(code: "KZT",name: "Kazakhstani Tenge (KZT)")
Currency.create(code: "LAK",name: "Laotian Kip (LAK)")
Currency.create(code: "LBP",name: "Lebanese Pound (LBP)")
Currency.create(code: "LKR",name: "Sri Lankan Rupee (LKR)")
Currency.create(code: "LRD",name: "Liberian Dollar (LRD)")
Currency.create(code: "LSL",name: "Lesotho Loti (LSL)")
Currency.create(code: "LYD",name: "Libyan Dinar (LYD)")
Currency.create(code: "MAD",name: "Moroccan Dirham (MAD)")
Currency.create(code: "MDL",name: "Moldovan Leu (MDL)")
Currency.create(code: "MGA",name: "Malagasy Ariary (MGA)")
Currency.create(code: "MKD",name: "Macedonian Denar (MKD)")
Currency.create(code: "MMK",name: "Myanma Kyat (MMK)")
Currency.create(code: "MNT",name: "Mongolian Tugrik (MNT)")
Currency.create(code: "MOP",name: "Macanese Pataca (MOP)")
Currency.create(code: "MRO",name: "Mauritanian Ouguiya (pre-2018) (MRO)")
Currency.create(code: "MRU",name: "Mauritanian Ouguiya (MRU)")
Currency.create(code: "MUR",name: "Mauritian Rupee (MUR)")
Currency.create(code: "MVR",name: "Maldivian Rufiyaa (MVR)")
Currency.create(code: "MWK",name: "Malawian Kwacha (MWK)")
Currency.create(code: "MXN",name: "Mexican Peso (MXN)")
Currency.create(code: "MYR",name: "Malaysian Ringgit (MYR)")
Currency.create(code: "MZN",name: "Mozambican Metical (MZN)")
Currency.create(code: "NAD",name: "Namibian Dollar (NAD)")
Currency.create(code: "NGN",name: "Nigerian Naira (NGN)")
Currency.create(code: "NOK",name: "Norwegian Krone (NOK)")
Currency.create(code: "NPR",name: "Nepalese Rupee (NPR)")
Currency.create(code: "NZD",name: "New Zealand Dollar (NZD)")
Currency.create(code: "OMR",name: "Omani Rial (OMR)")
Currency.create(code: "PAB",name: "Panamanian Balboa (PAB)")
Currency.create(code: "PEN",name: "Peruvian Nuevo Sol (PEN)")
Currency.create(code: "PGK",name: "Papua New Guinean Kina (PGK)")
Currency.create(code: "PHP",name: "Philippine Peso (PHP)")
Currency.create(code: "PKR",name: "Pakistani Rupee (PKR)")
Currency.create(code: "PLN",name: "Polish Zloty (PLN)")
Currency.create(code: "PYG",name: "Paraguayan Guarani (PYG)")
Currency.create(code: "QAR",name: "Qatari Rial (QAR)")
Currency.create(code: "RON",name: "Romanian Leu (RON)")
Currency.create(code: "RSD",name: "Serbian Dinar (RSD)")
Currency.create(code: "RUB",name: "Russian Ruble (RUB)")
Currency.create(code: "RUR",name: "Old Russian Ruble (RUR)")
Currency.create(code: "RWF",name: "Rwandan Franc (RWF)")
Currency.create(code: "SAR",name: "Saudi Riyal (SAR)")
Currency.create(code: "SCR",name: "Seychellois Rupee (SCR)")
Currency.create(code: "SDG",name: "Sudanese Pound (SDG)")
Currency.create(code: "SEK",name: "Swedish Krona (SEK)")
Currency.create(code: "SGD",name: "Singapore Dollar (SGD)")
Currency.create(code: "SHP",name: "Saint Helena Pound (SHP)")
Currency.create(code: "SLL",name: "Sierra Leonean Leone (SLL)")
Currency.create(code: "SOS",name: "Somali Shilling (SOS)")
Currency.create(code: "SRD",name: "Surinamese Dollar (SRD)")
Currency.create(code: "SYP",name: "Syrian Pound (SYP)")
Currency.create(code: "SZL",name: "Swazi Lilangeni (SZL)")
Currency.create(code: "THB",name: "Thai Baht (THB)")
Currency.create(code: "TJS",name: "Tajikistani Somoni (TJS)")
Currency.create(code: "TMT",name: "Turkmenistani Manat (TMT)")
Currency.create(code: "TND",name: "Tunisian Dinar (TND)")
Currency.create(code: "TOP",name: "Tongan Pa'anga (TOP)")
Currency.create(code: "TRY",name: "Turkish Lira (TRY)")
Currency.create(code: "TTD",name: "Trinidad and Tobago Dollar (TTD)")
Currency.create(code: "TWD",name: "New Taiwan Dollar (TWD)")
Currency.create(code: "TZS",name: "Tanzanian Shilling (TZS)")
Currency.create(code: "UAH",name: "Ukrainian Hryvnia (UAH)")
Currency.create(code: "UGX",name: "Ugandan Shilling (UGX)")
Currency.create(code: "USD",name: "United States Dollar (USD)")
Currency.create(code: "UYU",name: "Uruguayan Peso (UYU)")
Currency.create(code: "UZS",name: "Uzbekistan Som (UZS)")
Currency.create(code: "VND",name: "Vietnamese Dong (VND)")
Currency.create(code: "VUV",name: "Vanuatu Vatu (VUV)")
Currency.create(code: "WST",name: "Samoan Tala (WST)")
Currency.create(code: "XAF",name: "CFA Franc BEAC (XAF)")
Currency.create(code: "XAG",name: "Silver Ounce (XAG)")
Currency.create(code: "XAU",name: "Gold Ounce (XAU)")
Currency.create(code: "XCD",name: "East Caribbean Dollar (XCD)")
Currency.create(code: "XDR",name: "Special Drawing Rights (XDR)")
Currency.create(code: "XOF",name: "CFA Franc BCEAO (XOF)")
Currency.create(code: "XPF",name: "CFP Franc (XPF)")
Currency.create(code: "YER",name: "Yemeni Rial (YER)")
Currency.create(code: "ZAR",name: "South African Rand (ZAR)")
Currency.create(code: "ZMW",name: "Zambian Kwacha (ZMW)")
Currency.create(code: "ZWL",name: "Zimbabwean Dollar (ZWL)")